add verenigingen criterion
lblod/app-subsidiepunt pull request #21
Opened 2024-07-15 08:54 UTC by wolfderechter

## ID
DGS-292

## Description
Add new verenigingen criterion

## Type of change

 - [ ] Bug fix
 - [x] New feature
 - [ ] Breaking change
 - [ ] Maintanance

## How to setup
...

## How to test
...

2024-07-16 14:02 UTC, cecemel requested changes
besides the remarks, it should work. but the proof of the pudding will be in the eating.

2024-07-17 12:29 UTC, cecemel approved these changes
thanks. We'll soon find out if it works

2024-07-17 12:32 UTC, cecemel requested changes

2024-07-17 12:36 UTC, wolfderechter commented on config/migrations/2024/20240715104628-add-verenigingen-criterion.sparql
> +    <http://data.lblod.info/id/conceptscheme/c6157470-9fb3-4e8d-a9b7-8737dbfa3642>
For `<http://data.lblod.info/id/conceptscheme/ACMIDMOrganisationClassification>` as well?

2024-07-17 12:37 UTC, cecemel requested changes

2024-07-17 12:37 UTC, cecemel commented on config/migrations/2024/20240715104628-add-verenigingen-criterion.sparql
> +    <http://data.lblod.info/id/conceptscheme/c6157470-9fb3-4e8d-a9b7-8737dbfa3642>
no that last one makes sense. You have skos:Concept and thats != to a skos:Conceptscheme

2024-07-17 12:38 UTC, wolfderechter commented on config/migrations/2024/20240715104628-add-verenigingen-criterion.sparql
> +    <http://data.lblod.info/id/conceptscheme/c6157470-9fb3-4e8d-a9b7-8737dbfa3642>
I see, that makes sense!

2024-07-26 12:01 UTC, merged